### ISSUE TITLE
Mitsuba2 support

### ISSUE THREAD

**Issue by hxwork** [chrdiller/mitsuba-visualize#2]
Hi, 

Thanks for your awesome visualization code. Recently, the Mitsuba is updated to vision 2, and when I try to transfer this project to Mitsuba2, I failed to find the corresponding API. Do you have any code or plan to update this project to support mitsuba2?

Hao

**Comment by chrdiller** [comment]
Hi Hao,

I'm glad it's useful for you :) I haven't looked into mitsuba2 yet but would expect their new api to be quite different, making the transition non-trivial. For the time being, I can also recommend giving blender a shot for your visualisations, I found it  easier to use than mitsuba and it also comes with GPU rendering support out of the box.

**Comment by hxwork** [comment]
Thanks for your reply, I will try to use the blender.
